version: '3.8'

services:
  web:
    build:
      context: ./backend
    container_name: web
    volumes:
      - ./backend:/var/www/html
      - ./backend/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
      - MYSQL_DATABASE=my_database
    
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: user_password
    ports:
      - "8081:80"
    depends_on:
      - db

  react-app:
    image: node:17
    container_name: react-app
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

volumes:
  db_data:
